utilisateur:
    resource: "@UtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

perspective:
    resource: "@PerspectiveBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
