<?php

namespace Perspective\PerspectiveBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends EntityRepository
{
    public function findCommentaireByPublication($id){
        $req = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.publication =:id')
            ->orderBy('p.id')
            ->setParameter('id', $id);
        return $req->getQuery()->getResult();
    }

    public function bynbCommentaire($id){
        $req = $this->createQueryBuilder('p')



            ->where('p.publication =:id')
            ->select('count(p)')
            ->orderBy('p.id')
            ->setParameter('id', $id);
        return $req->getQuery()->getSingleScalarResult();
    }
}
