<?php

namespace Perspective\PerspectiveBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConsultationPubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultationPubRepository extends EntityRepository
{
    public function byNbConsultation($id){
        $req = $this->createQueryBuilder('p')

            ->join('p.publication','f')->select('f')

            ->where('f.id =:id')
            ->select('count(p)')
            ->orderBy('p.id')
            ->setParameter('id', $id);
        return $req->getQuery()->getSingleScalarResult();
    }
}
