<?php

namespace Perspective\PerspectiveBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends EntityRepository
{
    public function byUser($profile){
        $req = $this->createQueryBuilder('p')

            ->join('p.user','f')->select('f')

            ->where('f.username =:profile')
            ->select('p')
            ->orderBy('p.id')
            ->setParameter('profile', $profile);
        return $req->getQuery()->getResult();
    }

    public function findById($id){
        $req = $this->createQueryBuilder('p')




            ->select('p')
            ->where('p.id =:id')
            ->orderBy('p.id')
            ->setParameter('id', $id);
        return $req->getQuery()->getResult();
    }



}
