utilisateur_homepage:
    path:     /hello/{name}
    defaults: { _controller: UtilisateurBundle:Default:index }

profile:
    path:     /profile/{profile}
    defaults: { _controller: UtilisateurBundle:Utilisateur:index }

follow:
    path:     /follow/{id}
    defaults: { _controller: UtilisateurBundle:Follow:Follow }
